Sitegeist:
  Objects:
    plugins: {}
    rootNodeName: objects
    endpoints:
      neos/sitegeist/objects:
        querySchema: 'Sitegeist\Objects\GraphQl\RootQuery'
        mutationSchema: 'Sitegeist\Objects\GraphQl\RootMutation'

Neos:
  Flow:
    mvc:
      routes:
        Sitegeist.Objects:
          variables:
            endpoint: neos/sitegeist/objects
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Sitegeist.Objects:Controllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\Objects\Controller\.*'
  Neos:
    modules:
      management:
        submodules:
          objects:
            label: 'Neos.Neos:Modules:sitegeist.objects.label'
            icon: icon-database
            controller: \Sitegeist\Objects\Controller\ModuleController
            skipI18n: false
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            default:
              baseNodeType: 'Neos.Neos:Document,!Sitegeist.Objects:Object'
